export const ACTION_TYPES = {
    CHANGE_FIRST_NAME: "CHANGE_FIRST_NAME",
    CHANGE_LAST_NAME: "CHANGE_LAST_NAME",
    CHANGE_PHONE: "CHANGE_PHONE",
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_SELECT: "CHANGE_SELECT",
    CHANGE_TEXT_AREA: "CHANGE_TEXT_AREA"
}